#!/bin/bash

lib=lib-enigma-host-32-bit
#Compile Lib-Enigma For Host 32 bit (Linux).
echo "Building Lib-Enigma For Host 32 bit..."


cd "$(dirname $0)"
rm -rf $lib
mkdir $lib

gcc -m32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -Ofast -std=c99 -c lib-enigma.c -o $lib/lib-enigma.o
ar rcs $lib/libenigma.a $lib/lib-enigma.o