#!/bin/bash

lib=lib-enigma-mac-os-legacy
#Compile Lib-Enigma For Mac Legacy.
echo "Building Lib-Enigma For Legacy Mac OS..."


cd "$(dirname $0)"
rm -rf $lib
mkdir $lib

# -Ofast not avail in older clang.
gcc -O3 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -ffast-math -std=c99 -c lib-enigma.c -o $lib/lib-enigma.o
ar rcs $lib/libenigma.a $lib/lib-enigma.o
