#!/bin/bash

# Update this to update all example version numbers.
version=1.0.3

cd "$(dirname $0)"
rm -rf lib-enigma-host lib-enigma-host-32-bit lib-enigma-mac-os lib-enigma-mac-os-legacy lib-enigma-windows-i686 lib-enigma-windows-x86_64

if sed --version >/dev/null 2>&1; then
    echo "Info: using GNU sed"
    bsd_sed=false
else
    echo "Info: using BSD sed"
    bsd_sed=true
fi

if [ "$bsd_sed" == "true" ]; then
    sed -i '' -E "s|^VERSION=.*|VERSION=$version|" example-1-boot-file-printer/variables.mk
    sed -i '' -E "s|^VERSION=.*|VERSION=$version|" example-2-kings-field-1-english-translation-patcher/variables.mk
    sed -i '' -E "s|^VERSION=.*|VERSION=$version|" example-3-piracy-patcher/variables.mk
    sed -i '' -E "s|^VERSION=.*|VERSION=$version|" example-4-sector-viewer/variables.mk
else
    sed -i'' -E "s|^VERSION=.*|VERSION=$version|" example-1-boot-file-printer/variables.mk
    sed -i'' -E "s|^VERSION=.*|VERSION=$version|" example-2-kings-field-1-english-translation-patcher/variables.mk
    sed -i'' -E "s|^VERSION=.*|VERSION=$version|" example-3-piracy-patcher/variables.mk
    sed -i'' -E "s|^VERSION=.*|VERSION=$version|" example-4-sector-viewer/variables.mk
fi

(cd example-1-boot-file-printer && ../ezre/ezre -y)
(cd example-2-kings-field-1-english-translation-patcher && ../ezre/ezre -y)
(cd example-3-piracy-patcher && ../ezre/ezre -y)
(cd example-4-sector-viewer && ../ezre/ezre -y)

make -C example-1-boot-file-printer deps all
make -C example-2-kings-field-1-english-translation-patcher all
make -C example-3-piracy-patcher all
make -C example-4-sector-viewer all